// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: kvs/kvs.proto

package kvs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProtoGetBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []string               `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"` // Direct string array, more efficient than repeated structs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoGetBatchRequest) Reset() {
	*x = ProtoGetBatchRequest{}
	mi := &file_kvs_kvs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoGetBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoGetBatchRequest) ProtoMessage() {}

func (x *ProtoGetBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kvs_kvs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoGetBatchRequest.ProtoReflect.Descriptor instead.
func (*ProtoGetBatchRequest) Descriptor() ([]byte, []int) {
	return file_kvs_kvs_proto_rawDescGZIP(), []int{0}
}

func (x *ProtoGetBatchRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type ProtoGetBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"` // Direct string array, more efficient than repeated structs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoGetBatchResponse) Reset() {
	*x = ProtoGetBatchResponse{}
	mi := &file_kvs_kvs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoGetBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoGetBatchResponse) ProtoMessage() {}

func (x *ProtoGetBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kvs_kvs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoGetBatchResponse.ProtoReflect.Descriptor instead.
func (*ProtoGetBatchResponse) Descriptor() ([]byte, []int) {
	return file_kvs_kvs_proto_rawDescGZIP(), []int{1}
}

func (x *ProtoGetBatchResponse) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type ProtoPutBatchRequest struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Items         []*ProtoPutBatchRequest_Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoPutBatchRequest) Reset() {
	*x = ProtoPutBatchRequest{}
	mi := &file_kvs_kvs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoPutBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoPutBatchRequest) ProtoMessage() {}

func (x *ProtoPutBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kvs_kvs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoPutBatchRequest.ProtoReflect.Descriptor instead.
func (*ProtoPutBatchRequest) Descriptor() ([]byte, []int) {
	return file_kvs_kvs_proto_rawDescGZIP(), []int{2}
}

func (x *ProtoPutBatchRequest) GetItems() []*ProtoPutBatchRequest_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type ProtoPutBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoPutBatchResponse) Reset() {
	*x = ProtoPutBatchResponse{}
	mi := &file_kvs_kvs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoPutBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoPutBatchResponse) ProtoMessage() {}

func (x *ProtoPutBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kvs_kvs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoPutBatchResponse.ProtoReflect.Descriptor instead.
func (*ProtoPutBatchResponse) Descriptor() ([]byte, []int) {
	return file_kvs_kvs_proto_rawDescGZIP(), []int{3}
}

type ProtoPutBatchRequest_Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoPutBatchRequest_Item) Reset() {
	*x = ProtoPutBatchRequest_Item{}
	mi := &file_kvs_kvs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoPutBatchRequest_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoPutBatchRequest_Item) ProtoMessage() {}

func (x *ProtoPutBatchRequest_Item) ProtoReflect() protoreflect.Message {
	mi := &file_kvs_kvs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoPutBatchRequest_Item.ProtoReflect.Descriptor instead.
func (*ProtoPutBatchRequest_Item) Descriptor() ([]byte, []int) {
	return file_kvs_kvs_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ProtoPutBatchRequest_Item) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ProtoPutBatchRequest_Item) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_kvs_kvs_proto protoreflect.FileDescriptor

const file_kvs_kvs_proto_rawDesc = "" +
	"\n" +
	"\rkvs/kvs.proto\x12\x03kvs\"*\n" +
	"\x14ProtoGetBatchRequest\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\tR\x04keys\"/\n" +
	"\x15ProtoGetBatchResponse\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"|\n" +
	"\x14ProtoPutBatchRequest\x124\n" +
	"\x05items\x18\x01 \x03(\v2\x1e.kvs.ProtoPutBatchRequest.ItemR\x05items\x1a.\n" +
	"\x04Item\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x17\n" +
	"\x15ProtoPutBatchResponseB&Z$github.com/rstutsman/cs6450-labs/kvsb\x06proto3"

var (
	file_kvs_kvs_proto_rawDescOnce sync.Once
	file_kvs_kvs_proto_rawDescData []byte
)

func file_kvs_kvs_proto_rawDescGZIP() []byte {
	file_kvs_kvs_proto_rawDescOnce.Do(func() {
		file_kvs_kvs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kvs_kvs_proto_rawDesc), len(file_kvs_kvs_proto_rawDesc)))
	})
	return file_kvs_kvs_proto_rawDescData
}

var file_kvs_kvs_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_kvs_kvs_proto_goTypes = []any{
	(*ProtoGetBatchRequest)(nil),      // 0: kvs.ProtoGetBatchRequest
	(*ProtoGetBatchResponse)(nil),     // 1: kvs.ProtoGetBatchResponse
	(*ProtoPutBatchRequest)(nil),      // 2: kvs.ProtoPutBatchRequest
	(*ProtoPutBatchResponse)(nil),     // 3: kvs.ProtoPutBatchResponse
	(*ProtoPutBatchRequest_Item)(nil), // 4: kvs.ProtoPutBatchRequest.Item
}
var file_kvs_kvs_proto_depIdxs = []int32{
	4, // 0: kvs.ProtoPutBatchRequest.items:type_name -> kvs.ProtoPutBatchRequest.Item
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_kvs_kvs_proto_init() }
func file_kvs_kvs_proto_init() {
	if File_kvs_kvs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kvs_kvs_proto_rawDesc), len(file_kvs_kvs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kvs_kvs_proto_goTypes,
		DependencyIndexes: file_kvs_kvs_proto_depIdxs,
		MessageInfos:      file_kvs_kvs_proto_msgTypes,
	}.Build()
	File_kvs_kvs_proto = out.File
	file_kvs_kvs_proto_goTypes = nil
	file_kvs_kvs_proto_depIdxs = nil
}
