package kvs

// This code is generated by Claude Sonnet 4
import (
	"bufio"
	"fmt"
	"os"
	"runtime"
	"strconv"
	"strings"
	"sync"
	"time"
)

// HardwareMetrics represents the hardware utilization metrics
type HardwareMetrics struct {
	CPUUsagePercent     float64   `json:"cpu_usage_percent"`
	MemoryUsedMB        uint64    `json:"memory_used_mb"`
	MemoryTotalMB       uint64    `json:"memory_total_mb"`
	MemoryUsagePercent  float64   `json:"memory_usage_percent"`
	NetworkRxBitsPerSec uint64    `json:"network_rx_bits_per_sec"`
	NetworkTxBitsPerSec uint64    `json:"network_tx_bits_per_sec"`
	Timestamp           time.Time `json:"timestamp"`
}

// MetricsCollector collects hardware metrics with minimal overhead
type MetricsCollector struct {
	mu             sync.RWMutex
	lastCPUTotal   uint64
	lastCPUIdle    uint64
	lastNetworkRx  uint64
	lastNetworkTx  uint64
	lastSampleTime time.Time
	currentMetrics HardwareMetrics
	collecting     bool
	stopChan       chan struct{}

	// Statistics tracking
	sampleCount int
	cpuSum      float64
	cpuPeak     float64
	memSum      float64
	memPeak     float64
	netRxSum    uint64
	netRxPeak   uint64
	netTxSum    uint64
	netTxPeak   uint64
}

// NewMetricsCollector creates a new metrics collector
func NewMetricsCollector() *MetricsCollector {
	mc := &MetricsCollector{
		stopChan:       make(chan struct{}),
		lastSampleTime: time.Now(),
	}

	// Initialize baseline values
	mc.initBaseline()
	return mc
}

// StartCollection starts collecting metrics in the background
func (mc *MetricsCollector) StartCollection(interval time.Duration) {
	mc.mu.Lock()
	if mc.collecting {
		mc.mu.Unlock()
		return
	}
	mc.collecting = true
	mc.mu.Unlock()

	go mc.collectLoop(interval)
}

// StopCollection stops collecting metrics
func (mc *MetricsCollector) StopCollection() {
	mc.mu.Lock()
	defer mc.mu.Unlock()

	if !mc.collecting {
		return
	}

	mc.collecting = false
	close(mc.stopChan)
}

// GetCurrentMetrics returns the current hardware metrics
func (mc *MetricsCollector) GetCurrentMetrics() HardwareMetrics {
	mc.mu.RLock()
	defer mc.mu.RUnlock()
	return mc.currentMetrics
}

// collectLoop runs the collection loop
func (mc *MetricsCollector) collectLoop(interval time.Duration) {
	ticker := time.NewTicker(interval)
	defer ticker.Stop()

	for {
		select {
		case <-ticker.C:
			mc.updateMetrics()
		case <-mc.stopChan:
			return
		}
	}
}

// initBaseline initializes baseline values for CPU and network
func (mc *MetricsCollector) initBaseline() {
	// Initialize CPU baseline
	mc.lastCPUTotal, mc.lastCPUIdle = mc.readCPUStats()

	// Initialize network baseline
	mc.lastNetworkRx, mc.lastNetworkTx = mc.readNetworkStats()
}

// updateMetrics updates all metrics
func (mc *MetricsCollector) updateMetrics() {
	now := time.Now()
	timeDelta := now.Sub(mc.lastSampleTime).Seconds()

	// Update CPU usage
	cpuUsage := mc.getCPUUsage()

	// Update memory usage
	memUsed, memTotal, memPercent := mc.getMemoryUsage()

	// Update network usage
	netRxRate, netTxRate := mc.getNetworkUsage(timeDelta)

	mc.mu.Lock()
	mc.currentMetrics = HardwareMetrics{
		CPUUsagePercent:     cpuUsage,
		MemoryUsedMB:        memUsed,
		MemoryTotalMB:       memTotal,
		MemoryUsagePercent:  memPercent,
		NetworkRxBitsPerSec: netRxRate * 8, // Convert bytes to bits
		NetworkTxBitsPerSec: netTxRate * 8, // Convert bytes to bits
		Timestamp:           now,
	}
	mc.lastSampleTime = now

	// Update statistics
	mc.sampleCount++
	mc.cpuSum += cpuUsage
	if cpuUsage > mc.cpuPeak {
		mc.cpuPeak = cpuUsage
	}
	mc.memSum += memPercent
	if memPercent > mc.memPeak {
		mc.memPeak = memPercent
	}
	mc.netRxSum += netRxRate * 8
	if netRxRate*8 > mc.netRxPeak {
		mc.netRxPeak = netRxRate * 8
	}
	mc.netTxSum += netTxRate * 8
	if netTxRate*8 > mc.netTxPeak {
		mc.netTxPeak = netTxRate * 8
	}

	mc.mu.Unlock()
}

// readCPUStats reads CPU statistics from /proc/stat
func (mc *MetricsCollector) readCPUStats() (total, idle uint64) {
	file, err := os.Open("/proc/stat")
	if err != nil {
		return 0, 0
	}
	defer file.Close()

	scanner := bufio.NewScanner(file)
	if scanner.Scan() {
		line := scanner.Text()
		fields := strings.Fields(line)
		if len(fields) >= 5 && fields[0] == "cpu" {
			user, _ := strconv.ParseUint(fields[1], 10, 64)
			nice, _ := strconv.ParseUint(fields[2], 10, 64)
			system, _ := strconv.ParseUint(fields[3], 10, 64)
			idle, _ = strconv.ParseUint(fields[4], 10, 64)

			total = user + nice + system + idle
			if len(fields) > 5 {
				iowait, _ := strconv.ParseUint(fields[5], 10, 64)
				total += iowait
			}
			if len(fields) > 6 {
				irq, _ := strconv.ParseUint(fields[6], 10, 64)
				total += irq
			}
			if len(fields) > 7 {
				softirq, _ := strconv.ParseUint(fields[7], 10, 64)
				total += softirq
			}
		}
	}
	return
}

// getCPUUsage calculates CPU usage percentage
func (mc *MetricsCollector) getCPUUsage() float64 {
	total, idle := mc.readCPUStats()

	totalDelta := total - mc.lastCPUTotal
	idleDelta := idle - mc.lastCPUIdle

	mc.lastCPUTotal = total
	mc.lastCPUIdle = idle

	if totalDelta == 0 {
		return 0
	}

	return float64(totalDelta-idleDelta) / float64(totalDelta) * 100
}

// getMemoryUsage gets memory usage from runtime and /proc/meminfo
func (mc *MetricsCollector) getMemoryUsage() (used, total uint64, percent float64) {
	// Get process memory usage
	var m runtime.MemStats
	runtime.ReadMemStats(&m)
	used = m.Alloc / 1024 / 1024 // Convert to MB

	// Get system memory info
	file, err := os.Open("/proc/meminfo")
	if err != nil {
		return used, 0, 0
	}
	defer file.Close()

	scanner := bufio.NewScanner(file)
	var memTotalKB, memAvailableKB uint64

	for scanner.Scan() {
		line := scanner.Text()
		fields := strings.Fields(line)
		if len(fields) >= 2 {
			switch fields[0] {
			case "MemTotal:":
				memTotalKB, _ = strconv.ParseUint(fields[1], 10, 64)
			case "MemAvailable:":
				memAvailableKB, _ = strconv.ParseUint(fields[1], 10, 64)
			}
		}
	}

	total = memTotalKB / 1024 // Convert to MB
	if total > 0 {
		systemUsed := (memTotalKB - memAvailableKB) / 1024
		percent = float64(systemUsed) / float64(total) * 100
	}

	return
}

// readNetworkStats reads network statistics from /proc/net/dev
func (mc *MetricsCollector) readNetworkStats() (rxBytes, txBytes uint64) {
	file, err := os.Open("/proc/net/dev")
	if err != nil {
		return 0, 0
	}
	defer file.Close()

	scanner := bufio.NewScanner(file)
	// Skip header lines
	scanner.Scan()
	scanner.Scan()

	for scanner.Scan() {
		line := scanner.Text()
		fields := strings.Fields(line)
		if len(fields) >= 10 {
			iface := strings.TrimSuffix(fields[0], ":")
			// Skip loopback interface
			if iface == "lo" {
				continue
			}

			rx, _ := strconv.ParseUint(fields[1], 10, 64)
			tx, _ := strconv.ParseUint(fields[9], 10, 64)
			rxBytes += rx
			txBytes += tx
		}
	}
	return
}

// getNetworkUsage calculates network usage rate
func (mc *MetricsCollector) getNetworkUsage(timeDelta float64) (rxRate, txRate uint64) {
	rx, tx := mc.readNetworkStats()

	if timeDelta > 0 {
		rxRate = uint64(float64(rx-mc.lastNetworkRx) / timeDelta)
		txRate = uint64(float64(tx-mc.lastNetworkTx) / timeDelta)
	}

	mc.lastNetworkRx = rx
	mc.lastNetworkTx = tx

	return
}

// PrintMetrics prints current metrics in a formatted way
func (mc *MetricsCollector) PrintMetrics() {
	metrics := mc.GetCurrentMetrics()
	fmt.Printf("=== Hardware Utilization Metrics ===\n")
	fmt.Printf("CPU Usage: %.2f%%\n", metrics.CPUUsagePercent)
	fmt.Printf("Memory: %d MB / %d MB (%.2f%%)\n",
		metrics.MemoryUsedMB, metrics.MemoryTotalMB, metrics.MemoryUsagePercent)
	fmt.Printf("Network: RX %.2f Gbps, TX %.2f Gbps\n",
		float64(metrics.NetworkRxBitsPerSec)/1000000000,
		float64(metrics.NetworkTxBitsPerSec)/1000000000)
	fmt.Printf("Timestamp: %s\n", metrics.Timestamp.Format("2006-01-02 15:04:05"))
	fmt.Printf("=====================================\n")
}

// PrintFinalStats prints peak and average statistics
func (mc *MetricsCollector) PrintFinalStats() {
	mc.mu.RLock()
	defer mc.mu.RUnlock()

	if mc.sampleCount == 0 {
		fmt.Println("=== No metrics collected ===")
		return
	}

	avgCPU := mc.cpuSum / float64(mc.sampleCount)
	avgMem := mc.memSum / float64(mc.sampleCount)
	avgNetRx := float64(mc.netRxSum) / float64(mc.sampleCount) / 1000000000 // Convert to Gbps
	avgNetTx := float64(mc.netTxSum) / float64(mc.sampleCount) / 1000000000 // Convert to Gbps

	fmt.Printf("=== Final Hardware Utilization Statistics ===\n")
	fmt.Printf("CPU Usage:\n")
	fmt.Printf("  - Average: %.2f%%\n", avgCPU)
	fmt.Printf("  - Peak: %.2f%%\n", mc.cpuPeak)
	fmt.Printf("Memory Usage:\n")
	fmt.Printf("  - Average: %.2f%%\n", avgMem)
	fmt.Printf("  - Peak: %.2f%%\n", mc.memPeak)
	fmt.Printf("Network Usage:\n")
	fmt.Printf("  - Average RX: %.2f Gbps\n", avgNetRx)
	fmt.Printf("  - Peak RX: %.2f Gbps\n", float64(mc.netRxPeak)/1000000000)
	fmt.Printf("  - Average TX: %.2f Gbps\n", avgNetTx)
	fmt.Printf("  - Peak TX: %.2f Gbps\n", float64(mc.netTxPeak)/1000000000)
	fmt.Printf("Samples collected: %d\n", mc.sampleCount)
	fmt.Printf("==============================================\n")
}
